quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('authoradd/', views.author, name='author'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    path("author/<str:fullname>", views.author_page, name="author"),
]

quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

quotes/quoteapp/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=125, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=150, null=False, unique=True)
    born_date = models.CharField(max_length=150, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return f"{self.fullname}"


class Quote(models.Model):
    text = models.TextField(unique=True, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='quotes')
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.text}"

    def show_tags(self):
        tag = self.tags.all()
        return tag

    def show_quote_author(self):
        return self.author

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, ModelMultipleChoiceField, SelectMultiple
from .models import Tag, Quote, Author


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=125, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    text = CharField(required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'),
                                          widget=SelectMultiple(attrs={"class": "form-select", "size": "7"}))

    class Meta:
        model = Quote
        fields = ['text', 'author']
        exclude = ['tags']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=250, widget=TextInput())
    born_date = CharField(widget=TextInput())
    born_location = CharField(widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.decorators import login_required
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quote, Author


# Create your views here.
def main(request):
    quotes = Quote.objects.filter().all()
    return render(request, 'quoteapp/index.html', {"quotes": quotes})


def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})


def quote(request):
    tags = Quote.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_note = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': form})

    return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': QuoteForm()})


@login_required()
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/authoradd.html', {'form': form})

    return render(request, 'quoteapp/authoradd.html', {'form': AuthorForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quoteapp/detail.html', {"quote": quote})


@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quoteapp:main')


def author_page(request, fullname):
    authors = get_object_or_404(Author, fullname=fullname)

    return render(request, "quoteapp/author.html", {"author": authors})

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    {% if user.is_authenticated %}
    <ul>
        <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
        <li><a href="{% url 'quoteapp:author' %}" role="button">Add author</a></li>
        <li><a href="{% url 'quoteapp:tag' %}" role="button">Add tag</a></li>
    </ul>
    <ul>
        <li>Welcome <b>{{ user.username }}!</b></li>
        <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
        <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
        <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
    </ul>

    {% endif %}
</nav>

<h4>{{ author.fullname }}</h4>
Born {{ author.born_date }} {{ author.born_location }}
<hr>
<h4>About author</h4>
{{ author.description }}

{% endblock %}

quotes/quoteapp/templates/quoteapp/authoradd.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author full name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author description:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="http://quotes.toscrape.com/static/bootstrap.min.css">
    <link rel="stylesheet" href="http://quotes.toscrape.com/static/main.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> To the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{quote.author}}</h1>
<p>Quote: <b>{{quote.text}}</b></p>
<p>Tags: <small> {{ quote.tags|tags }} </small></p>
{% endblock %}

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="http://quotes.toscrape.com/static/bootstrap.min.css">
</head>
<body>
<main class="container">

    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
            <li><a href="{% url 'quoteapp:author' %}" role="button">Add author</a></li>
            <li><a href="{% url 'quoteapp:tag' %}" role="button">Add tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>

        {% endif %}
    </nav>
    {% for quote in quotes %}
    <div class="card">
        <div class="card-body">
            <a href="author/{{ quote.show_quote_author }}">{{ quote.author }}</a>
            <p class="card-text">{{ quote.text }}</p>
        </div>
    </div>
    {% if user.is_authenticated %}
    <ul>
        <li>
            <a href="{% url 'quoteapp:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
        </li>
    </ul>
    {% endif %}
    {% endfor %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </div>
</form>

{% endblock %}